# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    branches: ['main', 'master']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # ← izin push ke ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}  # ← otomatis tersedia, tidak perlu buat manual

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
